# 当 push sdk/v* tag 时运行，如：在本地执行 git push origin sdk/v1.0.0
# 实际逻辑见可复用工作流 publish.yml
name: Publish And Release (sdk)

on:
  push:
    tags:
      - 'sdk/v*'

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      package: packages/sdk
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GHP_TOKEN: ${{ secrets.GHP_TOKEN }}
